### ISSUE TITLE
Banner on main page should say Act 22, not Act 20

### ISSUE THREAD

**Issue by adamb** [jemn21819/HolbertoScholarship#1]

**Comment by jemn21819** [comment]
Hello Adam,

Fixed!

On Dec 24, 2021 9:04 AM, Adam Beguelin ***@***.***> wrote:

Assigned #1<https://github.com/jemn21819/HolbertoScholarship/issues/1> to @jemn21819<https://github.com/jemn21819>.

**Comment by jemn21819** [comment]
banner changed
