### ISSUE TITLE
site should be under https

### ISSUE THREAD

**Issue by adamb** [jemn21819/HolbertoScholarship#2]
Since the browsers shows it as 'insecure' it might make people worried about donating.  Can we get a cert on this?  

there are free certs available. I see that www.holbertonschoolpr.com has https...  Maybe we can move the site to /scholarships if that's easier.  But we would want a redirect since I'm sending this link out now... :-)

**Comment by jemn21819** [comment]
Yes I'm going to reuse the certificate form the main domain for the subdomains in this case the scholarship one today. I would let you know as soon as I get it done.

Jaime

On Dec 24, 2021 9:06 AM, Adam Beguelin ***@***.***> wrote:

Assigned #2<https://github.com/jemn21819/HolbertoScholarship/issues/2> to @jemn21819<https://github.com/jemn21819>.

**Comment by jemn21819** [comment]
Fixed!
